# Generated by Django 5.2.1 on 2025-05-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
