# Generated by Django 5.2.1 on 2025-06-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerceAPI', '0005_remove_order_cart_items_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
